export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_COMPLETED: "SET_PRODUCTS_COMPLETED",
  SELECTED_PRODUCTS: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ERROR: "ERROR",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_LOGIN_STATUS: "AUTH_LOGIN_STATUS",
};
